apiVersion: v1
kind: ConfigMap
metadata:
 name: pgadmin-config
 namespace: icgroup
 labels:
    app: pgadmin
    env: prod
data:
 servers.json: |
   {
       "Servers": {
         "1": {
           "Name": "PostgreSQL DB",
           "Group": "Servers",
           "Port": 5432,
           "Username": "odoo",
           "Host": "db-service",
           "SSLMode": "prefer",
           "MaintenanceDB": "postgres"
         }
       }
   }