apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: icgroup
  labels:
    app: pgadmin
    env: prod
type: Opaque
data:
  pgadmin-password: cGdhZG1pbi1wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  namespace: icgroup
  labels:
    app: db_odoo
    env: prod
type: Opaque
data:
 postgres-password: cG9zdGdyZXMtcGFzc3dvcmQ=